[package]
name = "lucid"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
chrono = "0.4"
clap = "4.5.9"

[[bin]]
name = "lucid-fuzz"
path = "src/main.rs"